In [11]:
# Data Manipulation
import numpy as np
import pandas as pd
import os
# Visualization/Image Processing
import cv2
import matplotlib.pyplot as plt
from tqdm import tqdm
# Machine Learning
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, Input, BatchNormalization, Flatten, MaxPool2D, Dense

# Other
from pathlib import Path

In [8]:
#Path to train images
Train_path_axial = Path('./axial_t1wce_2_class/images/train')
Train_path_coronal = Path('./coronal_t1wce_2_class/images/train')
Train_path_sagittal = Path('./sagittal_t1wce_2_class/images/train')

#Path to test images
Test_path_axial = Path('./axial_t1wce_2_class/images/test')
Test_path_coronal = Path('./coronal_t1wce_2_class/images/test')
Test_path_sagittal = Path('./sagittal_t1wce_2_class/images/test')


In [65]:
df = pd.read_csv('./axial_t1wce_2_class/labels/train/00095_170.txt',sep = ' ',names=["MGMT", "x1", "x2", "x3", "x4"], header = None)
img = cv2.imread('./axial_t1wce_2_class/images/train/00095_170')

with open('./axial_t1wce_2_class/labels/train/00095_170.txt', encoding="utf-8") as f:
    for line in f:
        num = list(map(float,line.split(" "))) #  line.split("\t") if numbers are seperated by tab
        print(num)
        for i in num:
            i = i * 255
            bb.append(i)
        print(num)
print(bb)
np.delete(bb,0)

[0.0, 0.428991, 0.361502, 0.144366, 0.150235]
[0.0, 0.428991, 0.361502, 0.144366, 0.150235]
[0.0, 109.392705, 92.18301, 36.81333, 38.309925]


array([109.392705,  92.18301 ,  36.81333 ,  38.309925])

In [141]:
lab = ['axial_t1wce_2_class','coronal_t1wce_2_class', 'sagittal_t1wce_2_class']
X_train = []
bb = []
temp_array  = []
for i in lab:
    folderPath = os.path.join('./',i,'images','train')
    for j in tqdm(os.listdir(folderPath)):
        img = cv2.imread(os.path.join(folderPath,j))
        X_train.append(img)
image_index = 0
for i in lab:
    labelsPath = os.path.join('./',i,'labels','train')
    bb = np.zeros((len(X_train),4))
    for j in tqdm(os.listdir(labelsPath)):
        with open(os.path.join(labelsPath,j), encoding="utf-8") as f:
            for line in f:
                num = list(map(float,line.split(" ")))
                temp_array = []
                for k in num:
                    k = k * X_train[image_index].shape[0]
                    temp_array.append(k)
                temp_array.pop(0)
                print(temp_array)
                bb[image_index] = np.array([temp_array])
                print(bb[image_index])
            image_index += 1

X_test = []
for i in lab:
    folderPath = os.path.join('./',i,'images','test')
    for j in tqdm(os.listdir(folderPath)):
         img = cv2.imread(os.path.join(folderPath,j))
         X_test.append(img)


 20%|████████████████▏                                                               | 60/296 [00:00<00:00, 590.80it/s]

[219.643392, 185.089024, 73.915392, 76.92032]
[219.643392 185.089024  73.915392  76.92032 ]
[226.8544, 191.398912, 72.713728, 99.154944]
[226.8544   191.398912  72.713728  99.154944]
[217.540096, 192.901632, 110.572544, 127.398912]
[217.540096 192.901632 110.572544 127.398912]
[218.441216, 196.206592, 128.0, 132.80768]
[218.441216 196.206592 128.       132.80768 ]
[224.150016, 198.309888, 121.389568, 123.793408]
[224.150016 198.309888 121.389568 123.793408]
[222.04672, 197.7088, 102.760448, 103.361536]
[222.04672  197.7088   102.760448 103.361536]
[221.746688, 196.206592, 98.553856, 90.74176]
[221.746688 196.206592  98.553856  90.74176 ]
[199.812096, 196.507136, 41.464832, 37.25824]
[199.812096 196.507136  41.464832  37.25824 ]
[178.028288, 169.464832, 18.328576, 23.436544]
[178.028288 169.464832  18.328576  23.436544]
[176.97664, 172.018688, 30.046976, 24.33792]
[176.97664  172.018688  30.046976  24.33792 ]
[175.323904, 170.666752, 30.948352, 30.046976]
[175.323904 170.666752  30.9483

 65%|██████████████████████████████████████████████████▉                            | 191/296 [00:00<00:00, 598.56it/s]

[119.186176, 112.22528, 52.882688, 45.37088]
[119.186176 112.22528   52.882688  45.37088 ]
[112.17536, 113.878016, 50.879488, 45.070336]
[112.17536  113.878016  50.879488  45.070336]
[112.17536, 114.328576, 39.66208, 45.37088]
[112.17536  114.328576  39.66208   45.37088 ]
[83.330304, 140.018688, 32.450816, 31.248896]
[ 83.330304 140.018688  32.450816  31.248896]
[108.16896, 159.549184, 33.25184, 27.042304]
[108.16896  159.549184  33.25184   27.042304]
[101.158144, 179.530496, 20.031232, 12.319232]
[101.158144 179.530496  20.031232  12.319232]
[108.369408, 166.009344, 43.267584, 32.150272]
[108.369408 166.009344  43.267584  32.150272]
[139.417856, 165.859072, 20.431872, 16.826368]
[139.417856 165.859072  20.431872  16.826368]
[72.313088, 165.25824, 21.633792, 21.633792]
[ 72.313088 165.25824   21.633792  21.633792]
[88.73856, 170.96704, 60.895232, 31.849728]
[ 88.73856  170.96704   60.895232  31.849728]
[86.735616, 173.37088, 53.683968, 33.65248]
[ 86.735616 173.37088   53.683968  33.65

100%|███████████████████████████████████████████████████████████████████████████████| 296/296 [00:00<00:00, 582.43it/s]


[219.943424, 215.136256, 22.835712, 27.643392]
[219.943424 215.136256  22.835712  27.643392]
[82.729216, 125.59616, 38.46016, 30.046976]
[ 82.729216 125.59616   38.46016   30.046976]
[84.131328, 126.497536, 49.276928, 48.075008]
[ 84.131328 126.497536  49.276928  48.075008]
[85.133056, 125.59616, 52.882688, 52.882688]
[ 85.133056 125.59616   52.882688  52.882688]
[87.336448, 126.497536, 58.090752, 55.286272]
[ 87.336448 126.497536  58.090752  55.286272]
[157.846528, 132.05632, 30.046976, 29.746432]
[157.846528 132.05632   30.046976  29.746432]
[86.935808, 126.647808, 58.090752, 54.384896]
[ 86.935808 126.647808  58.090752  54.384896]
[160.250368, 132.957696, 34.05312, 29.1456]
[160.250368 132.957696  34.05312   29.1456  ]
[89.94048, 125.445888, 52.081408, 54.384896]
[ 89.94048  125.445888  52.081408  54.384896]
[160.851456, 134.610432, 36.8576, 39.060992]
[160.851456 134.610432  36.8576    39.060992]
[93.345792, 126.197248, 42.866944, 49.276928]
[ 93.345792 126.197248  42.866944  49.27

  0%|                                                                                          | 0/318 [00:00<?, ?it/s]

[182.985728, 164.356608, 79.924736, 89.540096]
[182.985728 164.356608  79.924736  89.540096]
[186.2912, 156.845056, 52.882432, 43.267584]
[186.2912   156.845056  52.882432  43.267584]
[337.126912, 167.66208, 63.699456, 69.7088]
[337.126912 167.66208   63.699456  69.7088  ]
[178.17856, 159.54944, 87.136256, 100.356608]
[178.17856  159.54944   87.136256 100.356608]
[340.131328, 191.699456, 33.652736, 42.06592]
[340.131328 191.699456  33.652736  42.06592 ]
[188.093952, 158.04672, 68.507136, 55.286272]
[188.093952 158.04672   68.507136  55.286272]
[331.117568, 174.572544, 54.084608, 64.300544]
[331.117568 174.572544  54.084608  64.300544]
[339.830784, 192.0, 22.234624, 30.647808]
[339.830784 192.        22.234624  30.647808]
[178.17856, 159.849984, 84.732416, 103.361536]
[178.17856  159.849984  84.732416 103.361536]
[136.563456, 121.08928, 34.554112, 34.253568]
[136.563456 121.08928   34.554112  34.253568]
[189.295616, 159.849984, 70.910976, 56.488448]
[189.295616 159.849984  70.910976  56

 43%|██████████████████████████████████▎                                            | 138/318 [00:00<00:00, 691.06it/s]

[179.981312, 194.103296, 87.136256, 82.929664]
[179.981312 194.103296  87.136256  82.929664]
[286.948352, 190.798336, 109.971968, 83.530752]
[286.948352 190.798336 109.971968  83.530752]
[191.398912, 223.849984, 55.88736, 71.511552]
[191.398912 223.849984  55.88736   71.511552]
[167.962624, 235.868672, 40.262656, 61.896704]
[167.962624 235.868672  40.262656  61.896704]
[224.751104, 80.22528, 61.295616, 69.108224]
[224.751104  80.22528   61.295616  69.108224]
[323.30496, 46.873088, 51.680768, 40.863744]
[323.30496   46.873088  51.680768  40.863744]
[313.990656, 157.746688, 59.492864, 67.906048]
[313.990656 157.746688  59.492864  67.906048]
[186.591744, 194.704384, 47.474176, 43.267584]
[186.591744 194.704384  47.474176  43.267584]
[183.88736, 67.30496, 49.276928, 37.25824]
[183.88736   67.30496   49.276928  37.25824 ]
[187.19232, 109.37088, 76.319232, 56.488448]
[187.19232  109.37088   76.319232  56.488448]
[194.40384, 37.25824, 25.840128, 45.671424]
[194.40384   37.25824   25.840128  4

[178.779136, 188.69504, 71.511552, 63.699456]
[178.779136 188.69504   71.511552  63.699456]
[349.1456, 210.62912, 33.652736, 40.262656]
[349.1456   210.62912   33.652736  40.262656]
[196.507136, 108.469248, 55.286272, 52.281856]
[196.507136 108.469248  55.286272  52.281856]
[258.103296, 157.446144, 69.108224, 68.507136]
[258.103296 157.446144  69.108224  68.507136]
[216.939008, 112.976384, 34.8544, 40.863744]
[216.939008 112.976384  34.8544    40.863744]
[332.018688, 188.394496, 46.272512, 58.2912]
[332.018688 188.394496  46.272512  58.2912  ]
[190.497792, 168.262656, 60.093952, 76.92032]
[190.497792 168.262656  60.093952  76.92032 ]
[204.018688, 190.798336, 85.93408, 108.769792]
[204.018688 190.798336  85.93408  108.769792]
[180.882432, 136.11264, 73.314304, 51.07968]
[180.882432 136.11264   73.314304  51.07968 ]
[327.21152, 182.385152, 84.732416, 78.723072]
[327.21152  182.385152  84.732416  78.723072]
[167.962624, 135.511552, 30.647808, 36.657152]
[167.962624 135.511552  30.647808  

 66%|████████████████████████████████████████████████████▏                          | 210/318 [00:00<00:00, 697.88it/s]

[230.459904, 98.8544, 45.070336, 65.502208]
[230.459904  98.8544    45.070336  65.502208]
[335.023616, 170.666496, 73.915392, 64.901632]
[335.023616 170.666496  73.915392  64.901632]
[256.901632, 170.365952, 21.03296, 21.03296]
[256.901632 170.365952  21.03296   21.03296 ]
[217.239552, 149.03296, 66.704384, 80.525824]
[217.239552 149.03296   66.704384  80.525824]
[229.25824, 84.732416, 67.906048, 93.746688]
[229.25824   84.732416  67.906048  93.746688]
[176.976384, 181.784064, 82.328576, 81.126912]
[176.976384 181.784064  82.328576  81.126912]
[180.5824, 231.962624, 57.089024, 51.680768]
[180.5824   231.962624  57.089024  51.680768]
[349.446144, 108.769792, 46.272512, 34.8544]
[349.446144 108.769792  46.272512  34.8544  ]
[325.108224, 226.8544, 34.8544, 28.243968]
[325.108224 226.8544    34.8544    28.243968]
[158.948352, 191.398912, 60.69504, 55.88736]
[158.948352 191.398912  60.69504   55.88736 ]
[193.201664, 171.267584, 35.455488, 36.056576]
[193.201664 171.267584  35.455488  36.056

100%|███████████████████████████████████████████████████████████████████████████████| 318/318 [00:00<00:00, 729.00it/s]


[337.727488, 96.150016, 58.891776, 49.276928]
[337.727488  96.150016  58.891776  49.276928]
[349.1456, 114.779136, 33.652736, 49.276928]
[349.1456   114.779136  33.652736  49.276928]
[157.746688, 173.37088, 35.455488, 28.243968]
[157.746688 173.37088   35.455488  28.243968]
[170.96704, 167.962624, 66.704384, 66.704384]
[170.96704  167.962624  66.704384  66.704384]
[189.896704, 156.845056, 66.103296, 72.11264]
[189.896704 156.845056  66.103296  72.11264 ]
[221.1456, 149.03296, 68.507136, 68.507136]
[221.1456   149.03296   68.507136  68.507136]
[200.11264, 117.784064, 61.295616, 63.699456]
[200.11264  117.784064  61.295616  63.699456]
[180.5824, 170.365952, 60.69504, 70.309888]
[180.5824   170.365952  60.69504   70.309888]
[338.929664, 94.04672, 61.295616, 55.88736]
[338.929664  94.04672   61.295616  55.88736 ]
[192.300544, 163.154944, 60.093952, 70.309888]
[192.300544 163.154944  60.093952  70.309888]
[347.342848, 112.375808, 24.037376, 36.056576]
[347.342848 112.375808  24.037376  36.0

 31%|█████████████████████████▏                                                      | 83/264 [00:00<00:00, 819.09it/s]

[176.375808, 175.474176, 113.577472, 90.140672]
[176.375808 175.474176 113.577472  90.140672]
[177.878016, 171.868672, 98.553856, 97.352192]
[177.878016 171.868672  98.553856  97.352192]
[296.5632, 225.051648, 57.089024, 42.666496]
[296.5632   225.051648  57.089024  42.666496]
[237.971968, 240.075264, 60.093952, 54.685696]
[237.971968 240.075264  60.093952  54.685696]
[266.51648, 229.859328, 119.586816, 67.906048]
[266.51648  229.859328 119.586816  67.906048]
[265.614848, 213.333504, 76.92032, 36.056576]
[265.614848 213.333504  76.92032   36.056576]
[326.910976, 221.446144, 34.8544, 34.253312]
[326.910976 221.446144  34.8544    34.253312]
[247.586816, 244.5824, 74.51648, 34.8544]
[247.586816 244.5824    74.51648   34.8544  ]
[355.455488, 230.459904, 45.070336, 34.253312]
[355.455488 230.459904  45.070336  34.253312]
[359.962624, 225.95328, 56.488448, 54.084608]
[359.962624 225.95328   56.488448  54.084608]
[368.075264, 219.943424, 39.060992, 28.845056]
[368.075264 219.943424  39.060992

[242.779136, 139.117568, 57.690112, 65.502208]
[242.779136 139.117568  57.690112  65.502208]
[243.07968, 142.121984, 33.051648, 36.657152]
[243.07968  142.121984  33.051648  36.657152]
[282.74176, 164.657152, 35.455488, 32.45056]
[282.74176  164.657152  35.455488  32.45056 ]
[282.441216, 158.04672, 81.727488, 72.11264]
[282.441216 158.04672   81.727488  72.11264 ]
[284.544512, 155.943424, 95.54944, 60.69504]
[284.544512 155.943424  95.54944   60.69504 ]
[275.530752, 162.8544, 61.896704, 57.690112]
[275.530752 162.8544    61.896704  57.690112]
[328.11264, 206.422528, 62.497792, 100.356608]
[328.11264  206.422528  62.497792 100.356608]
[324.206592, 170.365952, 52.281856, 58.2912]
[324.206592 170.365952  52.281856  58.2912  ]
[322.704384, 224.45056, 43.267584, 52.281856]
[322.704384 224.45056   43.267584  52.281856]
[317.59616, 172.169216, 54.685696, 65.502208]
[317.59616  172.169216  54.685696  65.502208]
[282.441216, 210.929664, 56.488448, 55.286272]
[282.441216 210.929664  56.488448  5

100%|███████████████████████████████████████████████████████████████████████████████| 264/264 [00:00<00:00, 982.57it/s]

[234.666496, 215.136256, 78.723072, 78.121984]
[234.666496 215.136256  78.723072  78.121984]
[199.511552, 248.488448, 37.25824, 31.849984]
[199.511552 248.488448  37.25824   31.849984]
[229.25824, 221.446144, 84.732416, 101.558784]
[229.25824  221.446144  84.732416 101.558784]
[234.666496, 223.54944, 73.915392, 91.342848]
[234.666496 223.54944   73.915392  91.342848]
[231.060992, 215.737344, 51.07968, 60.093952]
[231.060992 215.737344  51.07968   60.093952]
[309.182976, 262.610432, 31.849984, 31.248896]
[309.182976 262.610432  31.849984  31.248896]
[249.089024, 152.037376, 35.455488, 44.469248]
[249.089024 152.037376  35.455488  44.469248]
[256.901632, 159.248896, 24.638464, 24.037376]
[256.901632 159.248896  24.638464  24.037376]
[259.30496, 157.1456, 60.69504, 61.896704]
[259.30496  157.1456    60.69504   61.896704]
[264.413184, 153.840128, 62.497792, 61.295616]
[264.413184 153.840128  62.497792  61.295616]
[258.704384, 162.553856, 49.878016, 42.666496]
[258.704384 162.553856  49.878


100%|█████████████████████████████████████████████████████████████████████████████████| 70/70 [00:00<00:00, 321.75it/s]


In [ ]:
def display_image(img, bbox_coords=[], pred_coords=[], norm=False):
    
    # Draw the bounding boxes
    if len(bbox_coords) == 4:
        xmin, ymin, xmax, ymax = bbox_coords
        img = cv2.rectangle(img, (int(xmin), int(ymin)), (int(xmax), int(ymax)), (0, 255, 0), 3)
        
    if len(pred_coords) == 4:
        xmin, ymin, xmax, ymax = pred_coords
        img = cv2.rectangle(img, (int(xmin), int(ymin)), (int(xmax), int(ymax)), (255, 0, 0), 3)
        
    plt.imshow(img)
    plt.xticks([])
    plt.yticks([])

In [117]:
len(X_train)

893

In [134]:
print(bb)

0.0
